SETLISTFM_API_KEY: 'WBs_jAc_rcRFQbwLMYKmLtiRZpocf2QzrHqt'
SETLIST_FM_URL: 'https://api.setlist.fm/rest/1.0/'
SPOTIFY_CLIENT: '71e77c5f36c14c3ba1432a31f40586f8'
SPOTIFY_KEY: 'd50b3ee88cc645e0a355b39e46760e8b'